# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Lab1.xdc

# IP: ip/clk_wiz_2/clk_wiz_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_2 || ORIG_REF_NAME==clk_wiz_2} -quiet] -quiet
